// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: com/appliedrec/verid3/serialization/capture3d/image_3d.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Image3D {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var jxl: Data = Data()

  var depthMap: DepthMap {
    get {return _depthMap ?? DepthMap()}
    set {_depthMap = newValue}
  }
  /// Returns true if `depthMap` has been explicitly set.
  var hasDepthMap: Bool {return self._depthMap != nil}
  /// Clears the value of `depthMap`. Subsequent reads from it will return its default value.
  mutating func clearDepthMap() {self._depthMap = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _depthMap: DepthMap? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Image3D: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "com.appliedrec.verid3.serialization.capture3d"

extension Image3D: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Image3D"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "jxl"),
    2: .standard(proto: "depth_map"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.jxl) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._depthMap) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.jxl.isEmpty {
      try visitor.visitSingularBytesField(value: self.jxl, fieldNumber: 1)
    }
    try { if let v = self._depthMap {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Image3D, rhs: Image3D) -> Bool {
    if lhs.jxl != rhs.jxl {return false}
    if lhs._depthMap != rhs._depthMap {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
